version: "3.8"

services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    image: al-folio:latest
    container_name: al-folio
    ports:
      - "8080:8080"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
      - jekyll-cache:/srv/jekyll/.jekyll-cache
      - jekyll-bundle:/usr/local/bundle
    environment:
      JEKYLL_ENV: development
    command: /tmp/entry_point.sh

volumes:
  jekyll-cache:
  jekyll-bundle:
